import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Pattern } from "./_components/pattern";
import { Footer } from "./_components/footer";
import { Header } from "./_components/header";
import {
  Sidebar,
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar";

const calSans = localFont({
  src: "./fonts/CalSans-SemiBold.woff",
  variable: "--font-heading",
});
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${calSans.variable} ${fontSans.variable} antialiased`}>
        <ThemeProvider>
          <SidebarProvider>
            <Sidebar />
            <Header />

            <SidebarInset>
              <Pattern />
              {children}
              <Footer />
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
